export default {
  equations: "",
  vectors: "",
  matrices: "Matrices",
  rank: "",
  inverse: "",
  transformations: "",
  gaussianElimination: "",
  vectorMatrixSpaces: "",
  orthogonality: "",
  projectionsLS: "",
  qrDecomposition: "",
  moorePenrose: "",
  determinants: "",
  eigendecomposition: "",
  eigenvaluesEigenvectors: "",
  svd: "",
  quadraticForms: "",
  definiteness: "",
  pca: "",
  hadamardProduct: "",
  crossProduct: "",
  broadcasting: ""
}
