export default {
  analysisOfAlgorithms: "",
  linkedLists: "",
  queues: "",
  stacks: "",
  unionFind: "",
  greedyAlgorithms: "",
  randomizedAlgorithms: "",
  primalityTesting: "",
  hashTables: "",
  bloomFilters: "",
  graphsNetworks: "Graphs & Networks",
  trees: "Trees",
  searchingSorting: "Searching & Sorting",
  dynamicProgramming: "Dynamic Programming",
  np: "",
  collections: "",
  bags: "",
  sets: ""
}
