export default {
    sequences: "",
    sumOperator: "",
    productOperator: "",
    convergentSequences: "",
    series: "",
    convergentSeries: "",
    realFunctions: "",
    continuousFunctions: "",
    convergentFunctions: "",
    limitRules: "",
    differentiableFunctions: "",
    riemannIntegrals: "",
    numericalIntegration: "",
    power: "",
    taylor: "",
    fourier: "",
    functionAnalysis: "",
}
  