export default {
  graphs: "",
  multirelational: "",
  storingGraphs: "",
  bfs: "",
  dfs: "",
  topologicalOrdering: "",
  shortestPath: "",
  allPairsShortestPath: "",
  eulerHamilton: "",
  mst: "",
  matchings: "",
  coloring: "",
  analysis: "Analyzing Graphs",
}
