export default {
  llms: "Large Language Models",
  courseraML: "",
  courseraDL: "",
  mainIdeas: "",
  knn: "",
  crossValidation: "",
  linear: "",
  ridge: "",
  lasso: "",
  logistic: "",
  naiveBayes: "",
  svm: "",
  kMeans: "",
  decisionTrees: "",
  randomForests: "",
  powerLaw: "",
  tfidf: "",
  miningDataStreams: "",
  findingSimilarItems: "",
  gradientDescent: "",
  backprop: "",
  mlp: "",
  correlation: "",
  correlationCross: "",
  correlationAuto: "",
  convolution: "",
  wordEmbeddings: "",
  linkAnalysis: "",
  pageRank: "",
  gnn: "",
}
