name: Chunk Documents
on: [push]
jobs:
  Chunk-Documents:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4.1.7
      with:
          fetch-depth: 0
    - name: Setup Python
      uses: actions/setup-python@v5.1.1
      with:
        python-version: 3.12.4
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./chunker/requirements.txt
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v44
    - name: List all changed files
      env:
        ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
      run: |
        for file in ${ALL_CHANGED_FILES}; do
          echo "$file was changed"
        done
