name: Chunk Documents
on: [push]
jobs:
  Chunk-Documents:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v4.1.7
    - name: Setup Python
      uses: actions/setup-python@v5.1.1
      with:
        python-version: 3.12.4
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./chunker/requirements.txt
